m_server_name: "m_server"
m_server_addr: "127.0.0.1:14711"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14722"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14733"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4711"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4722"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4733"

attacker_checkpoint: ""

# detector_checkpoint: ""
# detector_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/macta/outputs/2023-02-13/22-39-14/detector-999.pth"

# detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp1/detector-899.pth"
# detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp2/detector-899.pth"
# detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp3/detector-899.pth"

# detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp1/detector-1799.pth"
# detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp2/detector-1799.pth"
detector_checkpoint: "/checkpoint/yangxm/cache/ICLR2023/checkpoints/macta_20230222/exp3/detector-1799.pth"

train_device: "cuda:0"
infer_device: "cuda:2"
train_device_d: "cuda:1" #"cuda:2"
infer_device_d: "cuda:2" #"cuda:3"
num_train_rollouts: 72 #72 #48 #24
num_train_workers: 24  #24

num_eval_rollouts: 12 #2
num_eval_workers: 4 #2

#replay_buffer_size: 262144
#replay_buffer_size: 131072
replay_buffer_size: 65536
#replay_buffer_size: 1024
prefetch: 2

batch_size: 512
lr: 1e-4 #1e-4
entropy_coeff: 0.03 # default 0.01
learning_starts: 65536
push_every_n_steps: 10

dual_clip: 3.0

num_epochs: 100
steps_per_epoch: 3000

num_eval_episodes: 1000

train_seed: 123
eval_seed: 456

table_view: false

defaults:
  - env_config: exploit_env
  - model_config: transformer
