m_server_name: "m_server"
m_server_addr: "127.0.0.1:14711"

r_server_name: "r_server"
r_server_addr: "127.0.0.1:14722"

c_server_name: "c_server"
c_server_addr: "127.0.0.1:14733"

md_server_name: "md_server"
md_server_addr: "127.0.0.1:4711"

rd_server_name: "rd_server"
rd_server_addr: "127.0.0.1:4722"

cd_server_name: "cd_server"
cd_server_addr: "127.0.0.1:4733"

train_device: "cuda:0"
infer_device: "cuda:1"
train_device_d: "cuda:2" #"cuda:2"
infer_device_d: "cuda:3" #"cuda:3"

num_train_rollouts: 72 #72 #48 #24
num_train_workers: 24  #24

num_eval_rollouts: 12 #2
num_eval_workers: 4 #2

#attacker_checkpoint: "/data/home/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-10-31/18-20-26/ppo_agent-49.pth"
attacker_checkpoint: "/u/jxcui/Documents/CacheSimulator/src/rlmeta/outputs/2022-12-02/02-27-19/attacker-99.pth"

trace_files: [
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500-2M_500-4M.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_502-2M_502-4M.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_505-2M_505-4M.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_2000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_2000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_2000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_6000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_6000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_6000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_502_10000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_500_505_10000000.txt",
  "/u/jxcui/Documents/spectrace_bug_fix/spectrace_502_505_10000000.txt",
]
trace_limit: 2000000
legacy_trace_format: false

replay_buffer_size: 262144
prefetch: 2

batch_size: 512
lr: 1e-4
entropy_coeff: 0.03 # default 0.01
learning_starts: 65536
push_every_n_steps: 10

dual_clip: 3.0

num_epochs: 3000
steps_per_epoch: 3000

num_eval_episodes: 100

train_seed: 123
eval_seed: 456

table_view: false

defaults:
  - env_config: macta_env
  - model_config: transformer
