length_violation_reward: -20.0
double_victim_access_reward: -0.01
victim_access_reward: -0.01
correct_reward: 10.0
wrong_reward: -10.0
step_reward: -0.01

verbose: 0
force_victim_hit: false
flush_inst: false
allow_victim_multi_access: true
allow_empty_victim_access: false
attacker_addr_s: 8
attacker_addr_e: 15
victim_addr_s: 0
victim_addr_e: 7
reset_limit: 1
opponent_weights: [0.5, 0.5]

cache_configs:
  architecture:
    word_size: 1
    block_size: 1
    write_back: true
  cache_1:
    blocks: 8
    associativity: 1
    hit_time: 1
    rep_policy: "lru"
  mem:
    hit_time: 1000

window_size: 64
